//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_info()
        {
            this.Employee_Training = new HashSet<Employee_Training>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int DesignationId { get; set; }
        public string MobileNumber { get; set; }
        public int DistrictId { get; set; }
        public int BlockId { get; set; }
        public int FacilityId { get; set; }
        public Nullable<bool> Istrained { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int UserId { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<System.DateTime> TrainingCompletionYear { get; set; }
    
        public virtual BlockMaster BlockMaster { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual DesignationMaster DesignationMaster1 { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual FacilityMaster FacilityMaster { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Training> Employee_Training { get; set; }
    }
}
