//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Training
    {
        public int TrainingId { get; set; }
        public int MonthYearId { get; set; }
        public int DesignationId { get; set; }
        public int Employee_infoId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int UserId { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<int> BatchId { get; set; }
        public Nullable<bool> Istrained { get; set; }
    
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual DesignationMaster DesignationMaster1 { get; set; }
        public virtual Employee_info Employee_info { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
        public virtual MonthYearMaster MonthYearMaster { get; set; }
        public virtual tblBatchMaster tblBatchMaster { get; set; }
    }
}
