//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacilityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FacilityMaster()
        {
            this.Employee_info = new HashSet<Employee_info>();
            this.LoginMasters = new HashSet<LoginMaster>();
        }
    
        public int FacilityId { get; set; }
        public string FacilityName { get; set; }
        public string FacilityType { get; set; }
        public int DistrictID { get; set; }
        public int BlockID { get; set; }
        public System.DateTime AddDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int UserId { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string HFR_ID { get; set; }
        public string NIN { get; set; }
        public string Coordinate { get; set; }
        public string Status { get; set; }
    
        public virtual BlockMaster BlockMaster { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_info> Employee_info { get; set; }
        public virtual LoginMaster LoginMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginMaster> LoginMasters { get; set; }
    }
}
