//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class shsbTrainingEntities : DbContext
    {
        public shsbTrainingEntities()
            : base("name=shsbTrainingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockMaster> BlockMasters { get; set; }
        public virtual DbSet<DesignationMaster> DesignationMasters { get; set; }
        public virtual DbSet<DistrictMaster> DistrictMasters { get; set; }
        public virtual DbSet<Employee_info> Employee_info { get; set; }
        public virtual DbSet<Employee_Training> Employee_Training { get; set; }
        public virtual DbSet<FacilityMaster> FacilityMasters { get; set; }
        public virtual DbSet<Log_Table> Log_Table { get; set; }
        public virtual DbSet<LoginMaster> LoginMasters { get; set; }
        public virtual DbSet<MonthYearMaster> MonthYearMasters { get; set; }
        public virtual DbSet<ProcessType> ProcessTypes { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<tblBatchMaster> tblBatchMasters { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
    
        public virtual ObjectResult<SP_Report_TotalREgistration_Result> SP_Report_TotalREgistration(Nullable<int> distID)
        {
            var distIDParameter = distID.HasValue ?
                new ObjectParameter("DistID", distID) :
                new ObjectParameter("DistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Report_TotalREgistration_Result>("SP_Report_TotalREgistration", distIDParameter);
        }
    
        public virtual ObjectResult<SP_TotalStaffNurseUnTrained_Result> SP_TotalStaffNurseUnTrained(Nullable<int> distID)
        {
            var distIDParameter = distID.HasValue ?
                new ObjectParameter("DistID", distID) :
                new ObjectParameter("DistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalStaffNurseUnTrained_Result>("SP_TotalStaffNurseUnTrained", distIDParameter);
        }
    
        public virtual ObjectResult<SP_TotalTrainedANM_Result> SP_TotalTrainedANM(Nullable<int> distID)
        {
            var distIDParameter = distID.HasValue ?
                new ObjectParameter("DistID", distID) :
                new ObjectParameter("DistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalTrainedANM_Result>("SP_TotalTrainedANM", distIDParameter);
        }
    
        public virtual ObjectResult<SP_TotalTrainedStaffNurse_Result> SP_TotalTrainedStaffNurse(Nullable<int> distID)
        {
            var distIDParameter = distID.HasValue ?
                new ObjectParameter("DistID", distID) :
                new ObjectParameter("DistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalTrainedStaffNurse_Result>("SP_TotalTrainedStaffNurse", distIDParameter);
        }
    
        public virtual ObjectResult<SP_TotalUnTrainedANM_Result> SP_TotalUnTrainedANM(Nullable<int> distID)
        {
            var distIDParameter = distID.HasValue ?
                new ObjectParameter("DistID", distID) :
                new ObjectParameter("DistID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TotalUnTrainedANM_Result>("SP_TotalUnTrainedANM", distIDParameter);
        }
    }
}
