//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionPlanner.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistrictMaster()
        {
            this.LoginMasters = new HashSet<LoginMaster>();
            this.tblAcs = new HashSet<tblAc>();
        }
    
        public int Id { get; set; }
        public int DistCode { get; set; }
        public string DistrictNameEn { get; set; }
        public string DistrictNameHn { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginMaster> LoginMasters { get; set; }
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAc> tblAcs { get; set; }
    }
}
