//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionPlanner.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginMaster
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string NameSurname { get; set; }
        public string ImagePath { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> LastUpdateUserID { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string ContactNo { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> DistId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> AcId { get; set; }
    
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        public virtual tblAc tblAc { get; set; }
    }
}
