//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectionPlanner.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAc()
        {
            this.LoginMasters = new HashSet<LoginMaster>();
        }
    
        public int AC_NO { get; set; }
        public Nullable<int> DIST_NO { get; set; }
        public string AC_NAME_HN { get; set; }
        public string AC_NAME_EN { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual DistrictMaster DistrictMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginMaster> LoginMasters { get; set; }
    }
}
